tasks:
  - before: pip install -r requirements.txt
  - init: mkdocs build
  - command: mkdocs serve

# Ports to expose on workspace startup
ports:
  - port: 8000
    visibility: public
    onOpen: open-preview
