
tasks:
  - init: pipenv install & pipenv shell
    command: mkdocs serve

# Ports to expose on workspace startup
ports:
  - port: 8000
    visibility: public
    onOpen: open-preview

vscode:
  extensions:
    - DavidAnson.vscode-markdownlint