# Identity
site_name: Reflex
site_url: https://reflex.hopledge.fr/
site_author:  Reflex contributors
site_description: >-
  Already in a crisis ? Don't waste time, cheat

# Git
repo_name: Hopledge/reflex-content
repo_url: https://github.com/Hopledge/reflex-content
edit_uri: edit/main/

# Theme
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  language: en
  logo: assets/clover.png
  favicon: assets/clover.png
  icon:
    repo: fontawesome/brands/github
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - header.autohide
    - toc.integrate
    - search.suggest
    - content.code.annotate
  palette:
      scheme: slate
      primary: red
      accent: deep orange

# Extra and social icons
extra:
  generator: false # Made with material theme
copyright: CC BY-NC-SA 4.0

# Plugins
plugins:
  - search:
      lang: en
      prebuild_index: true
  - minify:
      minify_html: true
      minify_js: true
      htmlmin_opts:
          remove_comments: true
   # https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin
  - awesome-pages:
      filename: .pages
      strict: true

# Markdown extensions
markdown_extensions:
  - attr_list
  - abbr
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.smartsymbols
  - pymdownx.b64
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      linenums: true
      linenums_style: pymdownx-inline
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
